name: AutoSellChests
version: ${version}
main: com.italiarevenge.iRSellChest.AutoSellChests
api-version: 1.16
authors: [ Gypopo ]
description: AutoSellChests ported to work with IR-Shop
depend:
  - IR-Shop
  - Vault

softdepend:
  - Essentials
  - CMI
  - DecentHolograms
  - FancyHolograms

permissions:
  autosellchests.use:
    default: true
    description: "Allows to use the /autosellchests command"
  autosellchests.place:
    default: true
    description: "Allows to place a sell chest"
  autosellchests.pickup:
    default: true
    description: "Allows to pick up your own sell chest"
  autosellchests.show.all:
    description: "Allows to view info of a SellChest from a different player"
  autosellchests.maxchests.override:
    description: "Allows to place an infinite amount of chests"
  autosellchests.break:
    description: "Allows to break someone else chest"
  autosellchests.give:
    description: "Gives access to the /asc give command"
  autosellchests.view:
    description: "Gives access to the /asc view command"
  autosellchests.reload:
    description: "Gives access to the /asc reload command"
  autosellchests.remove:
    description: "Gives access to the /asc remove command"
